# Wine

In [118]:
import sklearn as sk

In [120]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2

In [122]:
from sklearn.datasets import load_wine
from sklearn import model_selection
from sklearn.metrics import confusion_matrix, classification_report 
import pandas as pd

# Load the wine dataset
wine_data = load_wine()

# Convert to DataFrame for easier handling
wine_df = pd.DataFrame(data=wine_data.data, columns=wine_data.feature_names)

# Add the target labels to the DataFrame
wine_df['target'] = wine_data.target

# Display the first few rows
print(wine_df.head())

   alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80
1    13.20        1.78  2.14               11.2      100.0           2.65
2    13.16        2.36  2.67               18.6      101.0           2.80
3    14.37        1.95  2.50               16.8      113.0           3.85
4    13.24        2.59  2.87               21.0      118.0           2.80

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04
1        2.76                  0.26             1.28             4.38  1.05
2        3.24                  0.30             2.81             5.68  1.03
3        3.49                  0.24             2.18             7.80  0.86
4        2.69                  0.39             1.82             4.32  1.04

   od280/od315_of_diluted_wines  proline  target
0                          3.92   1065.0       0
1                          3.40   1050.0       0
2                          3.17   1185.0       0
3                          3.45   1480.0       0
4                          2.93    735.0       0

In [124]:
print(wine_df.target)

0      0
1      0
2      0
3      0
4      0
      ..
173    2
174    2
175    2
176    2
177    2
Name: target, Length: 178, dtype: int64

In [125]:
wine_df.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,0.938202
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,0.775035
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,0.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,0.000000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,1.000000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,2.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,2.000000

In [128]:
print(wine_df['target'].value_counts())

target
1    71
0    59
2    48
Name: count, dtype: int64

## Task

**Your task is to classify this wine data using kNN. Try to predict the target value from the other factors. Don't forget to create a train/test split. You should print a confusion matrix and a classification report**

In [142]:
features = np.hstack([wine_df.values[::2, :-1], wine_df.values[1::2, :2]])
target = wine_df.values[1::2, -1]

X_train, X_test, y_train, y_test = model_selection.train_test_split(
    features, target, test_size=0.1, random_state=42
)

train_data = np.array(X_train, dtype=np.float32) 
labels = np.array(y_train, dtype=np.int32)      

knn = cv2.ml.KNearest_create() 
knn.train(train_data, cv2.ml.ROW_SAMPLE, labels)

test_data = np.array(X_test, dtype=np.float32)

ret, predictions, neighbors, dist = knn.findNearest(test_data, k=3)

print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions))

print("\nClassification Report:")
print(classification_report(y_test, predictions,zero_division=0))

Confusion Matrix:
[[1 2 1]
 [0 2 3]
 [0 0 0]]

Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      0.25      0.40         4
         1.0       0.50      0.40      0.44         5
         2.0       0.00      0.00      0.00         0

    accuracy                           0.33         9
   macro avg       0.50      0.22      0.28         9
weighted avg       0.72      0.33      0.42         9